Задание 1
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [40]:
x = np.arange( 0, 10 )
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#то же самое но с методом range()

In [42]:
x = np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
#Попытаемся перевернуть порядок элементов: с 10-го по 0-й в обратном порядке (-1)

In [44]:
x[10:0:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [45]:
#Ноль выпадает (последний элемент). Исправляем ситуацию:

In [46]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [47]:
#  напишем функцию, возвращающую numpy array с элементами от числа N до 0

In [48]:
def nump_arr_n(N):
    """функция возвращает numpy array с элементами от числа N до 0
    (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
    """
    x = np.arange( 0, N )
    return x[::-1]

In [49]:
#Проверим, как работает функция для N = 10

In [50]:
nump_arr_n(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [69]:
# создадим диагональную матрицу 5 х 5, в которой диагональные элементы идут 
# в обратном порядке (в предыдущем задании это было сделано)

In [70]:
matrix_1 = np.diag(np.arange(5)[::-1], k=0)
matrix_1

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [71]:
# С помощью list comprehension найдем диагональные элементы. Количество строк в матрице: matrix_1.shape[0]

In [72]:
[matrix_1[i][i] for i in range(matrix_1.shape[0])]

[4, 3, 2, 1, 0]

In [73]:
# Суммируем элементы

In [74]:
sum([matrix_1[i][i] for i in range(matrix_1.shape[0])])

10

In [75]:
# напишем функцию, возвращающую сумму значений диагонали диагональной матрицы с элементами от N до 0

In [76]:
def sum_diag_matrix(N):
    """возвращает сумму значений диагонали диагональной 
    матрицы с элементами от N до 0
    """
    matrix_1 = np.diag(np.arange(N)[::-1], k=0)
    return sum([matrix_1[i][i] for i in range(matrix_1.shape[0])])


In [77]:
# проверим для значения N=10

In [78]:
sum_diag_matrix(5)

10

Задание 3
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 
Определите какому фильму было выставлено больше всего оценок 5.0.

In [31]:
#скачал ml-latest-small.zip (size: 1 MB). Используем файл ratings

In [32]:
#импортируем библиотеку
import pandas as pd

In [33]:
ratings = pd.read_csv('ratings.csv')
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [34]:
#названия фильмов возьмем из movies

In [35]:
movies = pd.read_csv('movies.csv')
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [36]:
#сджоиним две таблицы по полю movieId

In [37]:
joined = ratings.merge(movies, on='movieId', how='left')
joined.head()

userId  movieId  rating  timestamp                        title  \
0       1        1     4.0  964982703             Toy Story (1995)   
1       1        3     4.0  964981247      Grumpier Old Men (1995)   
2       1        6     4.0  964982224                  Heat (1995)   
3       1       47     5.0  964983815  Seven (a.k.a. Se7en) (1995)   
4       1       50     5.0  964982931   Usual Suspects, The (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                               Comedy|Romance  
2                        Action|Crime|Thriller  
3                             Mystery|Thriller  
4                       Crime|Mystery|Thriller

In [38]:
#пока просто проверим, как работает фильтр. Найдем фильмы со словом 'Moscow'

In [39]:
joined[joined['title'].str.contains('Moscow', case=False)]['title'].unique()

array(['Don Camillo in Moscow (1965)', 'Moscow on the Hudson (1984)',
       'Moscow Does Not Believe in Tears (Moskva slezam ne verit) (1979)',
       'Police Academy: Mission to Moscow (1994)'], dtype=object)

In [40]:
#создадим таблицу top_films, в которую попадут только те фильмы, которые имеют хотя бы одну пятерку в ретингах

In [41]:
top_films = joined[(joined['rating']==5.0) ]
top_films.head()

userId  movieId  rating  timestamp                        title  \
3       1       47     5.0  964983815  Seven (a.k.a. Se7en) (1995)   
4       1       50     5.0  964982931   Usual Suspects, The (1995)   
6       1      101     5.0  964980868         Bottle Rocket (1996)   
8       1      151     5.0  964984041               Rob Roy (1995)   
9       1      157     5.0  964984100        Canadian Bacon (1995)   

                           genres  
3                Mystery|Thriller  
4          Crime|Mystery|Thriller  
6  Adventure|Comedy|Crime|Romance  
8        Action|Drama|Romance|War  
9                      Comedy|War

In [42]:
#Выведем первые пять фильмов с наибольшим количеством пятерок в оценках
top_films['title'].value_counts().head()

Shawshank Redemption, The (1994)             153
Pulp Fiction (1994)                          123
Forrest Gump (1994)                          116
Matrix, The (1999)                           109
Star Wars: Episode IV - A New Hope (1977)    104
Name: title, dtype: int64

In [43]:
#Выведем лидера по кол-ву пятерок
top_films['title'].value_counts().idxmax()

'Shawshank Redemption, The (1994)'

Задание 4
По данным файла power.csv посчитайте суммарное потребление 
стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 
за период с 2005 по 2010 года. 
Не учитывайте в расчетах отрицательные значения quantity.

In [45]:
# создадим таблицу consumtion
consumtion = pd.read_csv('power.csv')
consumtion.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [64]:
#для начала узнаем, как пишутся страны, т.к. Литву найти не удалось
consumtion[ consumtion['country'].str.contains('Lit', case=False) ]['country'].unique()

array(['Lithuania'], dtype=object)

In [65]:
consumtion[ consumtion['country'].str.contains('Lat', case=False) ]['country'].unique()

array(['Latvia'], dtype=object)

In [66]:
consumtion[ consumtion['country'].str.contains('Esto', case=False) ]['country'].unique()

array(['Estonia'], dtype=object)

In [ ]:
# попытался через query, но не ясно, как объединить несколько условий запроса

In [56]:
consumtion.query('{} <= year <= {}'.format(1996, 2000)).head()

country  year  quantity  category
0   Austria  1996       5.0         1
8   Czechia  1998       1.0         1
20  Finland  2000       0.0         1
21  Finland  1999       0.0         1
22  Finland  1998       0.0         1

In [ ]:
# получается сложный фильтр, нельзя как-то его проще написать?

In [101]:
filtered_consumtion = consumtion[((consumtion['country']=='Lithuania') | (consumtion['country']=='Latvia') | (consumtion['country']=='Estonia')) 
                                & ((consumtion['category']==4) | (consumtion['category']==12) | (consumtion['category']==21))
                                    & ((consumtion['year'] >= 2005) & (consumtion['year'] <= 2010)) 
                                        & (consumtion['quantity'] >= 0)]
filtered_consumtion.head()

country  year  quantity  category
10617    Estonia  2008       1.0         4
10618    Estonia  2007       0.0         4
10619    Estonia  2006       0.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4

In [106]:
#просуммируем по полю quantity

In [107]:
sum_consumption = filtered_consumtion['quantity'].sum()
sum_consumption

240580.0

Задание 5
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [ ]:
#приведем уравнения в упорядоченный вид 
# 4x + 2y + z = 4
# x + 3y + 0z = 12
# 0x + 5y + 4z = -3

In [14]:
a = np.array( [ [4, 2, 1], [1, 3, 0] , [0, 5, 4] ] )

In [15]:
b = np.array( [4, 12, -3] )

In [16]:
from numpy import linalg

In [ ]:
#Импортируем библиотеку и получаем решение

In [17]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [7]:
a = np.array( [ [4, 2, 1], [1, 3] , [5, 4, 3]])

In [ ]:
#Проверим решение

In [18]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [ ]:
#Проверим на калькуляторе

In [21]:
4 * 0.46666667 + 2 * 3.84444444 -5.55555556

4.0