Списки и строки:
1. Дан произвольный список, содержащий только числа. Выведите результат сложения всех чисел больше 10. 

In [ ]:
# первоначальное  решение

In [1]:
def list_number_addition(list_number):
    """Функция получает на вход список, содержащий только числа. 
    Выводит сумму только тех чиселиз списка, которые больше 10"""
    answer = 0
    for number in list_number:
        if number > 10:
            answer += number
    return answer
            

In [2]:
#проверим для произвольного списка
list_number = [1, 3, 14, 26, -5]

In [3]:
list_number_addition(list_number)

40

In [8]:
# более оптимальное решение на numpy
import numpy as np
numpy_numbers = np.array(list_number)
greater_10 = numpy_numbers[numpy_numbers>10]
sum_ = sum(greater_10)
sum_

40

2. Пусть задан список, содержащий строки. Выведите все строки, заканчивающиеся буквой r.

In [11]:
# первоначальное решение
def list_r(string_list):
    """Функция получает на вход список, содержащий только строки. 
    Выводит все строки, заканчивающиеся буквой r"""
    for string in string_list:
        if string[-1] == 'r':
            print(string)

In [12]:
#проверим для произвольного списка
string_list = ['return', 'docker', 'dzhumurat', 'r+r_', ' error ', 'r%', 'horror']

In [13]:
list_r(string_list)

docker
horror


In [17]:
# добавим пустую строку в список
string_list = ['return', 'docker', 'dzhumurat', 'r+r_', ' error ', 'r%', 'horror', '']
list_r(string_list)

docker
horror


IndexError: string index out of range

In [15]:
# доработанное решение (при наличии пустой строки '' в списке ошибки не будет)
string_list = ['return', 'docker', 'dzhumurat', 'r+r_', ' error ', 'r%', 'horror', '']
print([x for x in string_list if str(x).endswith('r')])

['docker', 'horror']


In [18]:
# менее элегантный, но тоже работающий вариант
def list_r(string_list):
    """Функция получает на вход список, содержащий только строки. 
    Выводит все строки, заканчивающиеся буквой r"""
    for string in string_list:
        try:
            if string[-1] == 'r':
                print(string)
        except IndexError:
            pass

In [19]:
string_list = ['return', 'docker', 'dzhumurat', 'r+r_', ' error ', 'r%', 'horror', '']
list_r(string_list)

docker
horror


3. Сгенерируйте и выведите cлучайную строку размером 6 символов, содержащую только цифры. Строка должна
содержать хотя бы одну цифру 3.

In [18]:
import string
import random

In [20]:
#строка с возможными цифрами
string.digits

'0123456789'

In [21]:
#используем лист компрехенш для списка из 6 элементов
[random.choice(string.digits) for _ in range(6)]

['3', '9', '3', '9', '8', '5']

In [28]:
#сделаем из списка строку через метод join 
''.join([random.choice(string.digits) for _ in range(6)])

'924397'

In [29]:
def random_list(string_length):
    """функция возвращает cлучайную строку размером 6 символов, 
    содержащую только цифры, одна из которых обязательно 3. """
    x = [random.choice(string.digits) for _ in range(string_length)]
    if '3' in x:
        return ''.join(x)
    else:
        return random_list(string_length)

In [30]:
#проверим
random_list(6)

'958317'

4. Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов

In [34]:
some_string = 'Не секрет, что Python не оптимизирует хвостовую рекурсию. Более того сам Гвидо является противником этого.'

In [78]:
#количество символов:
len(some_string) 

106

In [84]:
# удалим ненужные разделители и заменим их на пробелы
some_string.replace(',', ' ').replace('.', ' ')

'Не секрет  что Python не оптимизирует хвостовую рекурсию  Более того сам Гвидо является противником этого '

In [85]:
# применим метод split(), чтобы разбить строку на список из отдельных слов
some_string.replace(',', ' ').replace('.', ' ').split()

['Не',
 'секрет',
 'что',
 'Python',
 'не',
 'оптимизирует',
 'хвостовую',
 'рекурсию',
 'Более',
 'того',
 'сам',
 'Гвидо',
 'является',
 'противником',
 'этого']

In [86]:
# посчитаем кол-во слов
len(some_string.replace(',', ' ').replace('.', ' ').split())

15

In [87]:
def string_information(some_string):
    """функция принимает строку и выдает информацию о количестве символов и слов.
    Пример ответа: 'Количество символов = 106; Количество слов = 15'"""
    a = len(some_string) 
    b = len(some_string.replace(',', ' ').replace('.', ' ').split())
    return 'Количество символов = {}; Количество слов = {}'.format(a,b) 

In [88]:
#проверим
string_information(some_string)

'Количество символов = 106; Количество слов = 15'

In [89]:
# есть более универсальный готовый способ при помощи библиотеки re
import re

In [90]:
re.findall(r"[\w']+", some_string)

['Не',
 'секрет',
 'что',
 'Python',
 'не',
 'оптимизирует',
 'хвостовую',
 'рекурсию',
 'Более',
 'того',
 'сам',
 'Гвидо',
 'является',
 'противником',
 'этого']

In [93]:
#можно перечислить разделители в квадратных скобках
re.split("[, \-!?:]+", some_string)   

['Не',
 'секрет',
 'что',
 'Python',
 'не',
 'оптимизирует',
 'хвостовую',
 'рекурсию.',
 'Более',
 'того',
 'сам',
 'Гвидо',
 'является',
 'противником',
 'этого.']

Матрицы. 
1. Пусть дана матрица чисел размером NхN. Представьте данную матрицу в виде списка. Выведите результат сложения
всех элементов матрицы

In [20]:
import numpy as np

In [150]:
#создадим нулевую матрицу на 3 строки 3 столбцов
some_matrix = np.zeros((3,3))
some_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [151]:
#добавим несколько значений

In [152]:
some_matrix = np.append(some_matrix, [[4,13,54,7,0]])

In [167]:
some_matrix.ravel()

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4., 13., 54.,  7.,
        0.])

In [168]:
some_matrix

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4., 13., 54.,  7.,
        0.])

In [169]:
#просумммируем элементы
sum(some_matrix)

78.0

2. Пусть дана матрица чисел размером NхM. Найти столбец матрицы с максимальной суммой элементов.


In [21]:
# берем какую-то матрицу
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [ ]:
#транспонируем

In [22]:
np.array(users_stats).T

array([[2, 1, 2, 1, 0, 0, 1, 0, 0, 1],
       [1, 1, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 2, 1, 2, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 2, 0, 0, 0, 1, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 5, 0, 0, 3, 4]])

In [23]:
#Находим максимальное значение
m = []
for i in np.array(users_stats).T:
    m.append(sum(i))
max(m)

13

In [26]:
m

[8, 4, 7, 7, 2, 13]

In [29]:
# второй вариант решения
import numpy as np
matrix = np.array(users_stats).T
print(matrix.sum(axis=1).max())

13


In [31]:
# или так
users_stats.sum(axis=0).max()

13

Работа с динамичными структурами.
1. Пусть список студентов представлен в виде структуры [[No, ФИО, Возраст,Группа],[No, ФИО, Возраст, Группа],[No, ФИО,
Возраст, Группа]]. Преобразуйте список в словарь вида: {No: [ФИО, Возраст, Группа], No:[....], No: [....]}


In [248]:
# создадим матрицу
students = [
        [1, 'Ivanov Ivan Ivanovich', 17, 'Economy'],
        [2, 'Petrov Petr Petrovich', 19, 'Math'],
        [3, 'Sidorov Sidor Sidorovich', 21, 'Geography']
]

In [249]:
# посмотрим, что получилось
students

[[1, 'Ivanov Ivan Ivanovich', 17, 'Economy'],
 [2, 'Petrov Petr Petrovich', 19, 'Math'],
 [3, 'Sidorov Sidor Sidorovich', 21, 'Geography']]

In [250]:
#количество строк в матрице, которые нужно разбить
len(students)

3

In [251]:
#создаем словарь
{students[n][0]:students[n][1:] for n in range(len(students))}

{1: ['Ivanov Ivan Ivanovich', 17, 'Economy'],
 2: ['Petrov Petr Petrovich', 19, 'Math'],
 3: ['Sidorov Sidor Sidorovich', 21, 'Geography']}

2. Добавьте к задаче No6 для словаря возможность (без преобразования словаря обратно в список) изменить группу
студента. Поиск по «ФИО» («ФИО» студента и новый номер группы необходимо ввести с клавиатуры).

In [252]:
#выведем наш словарь со студентами
students_dict = {students[n][0]:students[n][1:] for n in range(len(students))}
students_dict

{1: ['Ivanov Ivan Ivanovich', 17, 'Economy'],
 2: ['Petrov Petr Petrovich', 19, 'Math'],
 3: ['Sidorov Sidor Sidorovich', 21, 'Geography']}

In [253]:
#при обращении к ключу словаря получаем значение
students_dict[1]

['Ivanov Ivan Ivanovich', 17, 'Economy']

In [254]:
student = input('Введите номер студента: ')
subject = input('Введите группу: ')

Введите номер студента: 1
Введите группу: Data Science


In [255]:
#получили значение номера студента
student

'1'

In [256]:
#получили значение группы
subject

'Data Science'

In [257]:
#заменяем последнее значение в ключе словаря. Введенные значение преобразуемв нужный тип
students_dict[int(student)][-1] = str(subject)

In [258]:
#проверяем результат

In [259]:
students_dict

{1: ['Ivanov Ivan Ivanovich', 17, 'Data Science'],
 2: ['Petrov Petr Petrovich', 19, 'Math'],
 3: ['Sidorov Sidor Sidorovich', 21, 'Geography']}

3. Добавьте к задаче No6 для словаря возможность (без преобразования словаря обратно в список) изменить возраст
студента. 

In [261]:
student = input('Введите номер студента: ')
age = input('Введите возраст студента: ')

Введите номер студента: 1
Введите возраст студента: 15


In [262]:
#заменяем второе значение в ключе словаря. Введенные значение преобразуемв нужный тип
students_dict[int(student)][1] = int(age)

In [263]:
#проверяем
students_dict

{1: ['Ivanov Ivan Ivanovich', 15, 'Data Science'],
 2: ['Petrov Petr Petrovich', 19, 'Math'],
 3: ['Sidorov Sidor Sidorovich', 21, 'Geography']}